### ISSUE TITLE
Prices undefined fetching crawler_cache_${crawler} table

### ISSUE THREAD

**Issue by liamtsang** [ulixee/platform#205]
I am trying using to use the Ulixee client to fetch the data from the cache of my crawler, but it returns this error:

I tried adding basePrice: 0  and that didn't help. I also tried testing it in docker vs local on my machine and it did not change anything either.
```
TypeError: Cannot read properties of undefined (reading 'prices')
    at QueryRunner.getCallPricing (/app/ulixee/datastore/core/lib/QueryRunner.ts:255:7)
    at QueryRunner.finalize (/app/ulixee/datastore/core/lib/QueryRunner.ts:201:28)
    at DatastoreApiHandler.handler (/app/ulixee/datastore/core/endpoints/Datastore.stream.ts:65:26)
    at async DatastoreApiHandler.handler (/app/ulixee/node_modules/specification/utils/ValidatingApiHandler.ts:34:12)
    at async ConnectionToClient.handleRequest (/app/ulixee/node_modules/net/lib/ConnectionToClient.ts:71:14)
------REMOTE CORE---------------------------------
  at Function.reviver (/home/liamt/Websites/grailed-data-ulixee/client/node_modules/commons/lib/TypeSerializer.ts:251:26)
    at JSON.parse (<anonymous>)
    at Function.parse (/home/liamt/Websites/grailed-data-ulixee/client/node_modules/commons/lib/TypeSerializer.ts:31:17)
    at WsTransportToCore.onMessage (/home/liamt/Websites/grailed-data-ulixee/client/node_modules/net/lib/WsTransportToCore.ts:105:36)
    at WebSocket.emit (node:events:517:28)
    at WebSocket.emit (node:domain:489:12)
    at Receiver.receiverOnMessage (/home/liamt/Websites/grailed-data-ulixee/client/node_modules/ws/lib/websocket.js:1220:20)
    at Receiver.emit (node:events:517:28)
    at Receiver.emit (node:domain:489:12)
    at Receiver.dataMessage (/home/liamt/Websites/grailed-data-ulixee/client/node_modules/ws/lib/receiver.js:596:14)
------CONNECTION----------------------------------
  at new Resolvable (/home/liamt/Websites/grailed-data-ulixee/client/node_modules/commons/lib/Resolvable.ts:19:18)
    at createPromise (/home/liamt/Websites/grailed-data-ulixee/client/node_modules/commons/lib/utils.ts:147:10)
    at PendingMessages.create (/home/liamt/Websites/grailed-data-ulixee/client/node_modules/net/lib/PendingMessages.ts:47:44)
    at ConnectionToCore.sendRequest (/home/liamt/Websites/grailed-data-ulixee/client/node_modules/net/lib/ConnectionToCore.ts:158:50)
    at async DatastoreApiClient.runApi (/home/liamt/Websites/grailed-data-ulixee/client/datastore/main/lib/DatastoreApiClient.ts:474:12)
    at async /home/liamt/Websites/grailed-data-ulixee/client/datastore/main/lib/DatastoreApiClient.ts:193:24
```
    
  ### client.ts: 
```js
import Client from '@ulixee/client';

async function main() {
  const client = new Client('ulx://localhost:1818/grailed-trends@1.1.1');
  const results = await client.fetch('crawler_cache_getAllBrands').then(records => {
    console.log(records)
  })
  await client.disconnect()
}

main().catch(console.error)
```

### datastore.ts:

```js
import { Table } from '@ulixee/datastore';
import { HeroExtractorPlugin, Crawler, Extractor, Datastore } from '@ulixee/datastore-plugins-hero';
import { string, number, date } from '@ulixee/schema';


const datastore = new Datastore({
  id: 'grailed-trends',
  version: '1.1.1',
  name: 'Grailed Trends',
  description: `A Datastore to read from the grailed post quantity by brand.`,
  crawlers: {
    getAllBrands: new Crawler({
      description: 'Test',
      basePrice: 0,
      async run({Hero}) {
        const hero = new Hero({
        // Removed proxy info
        });
        console.log("Starting crawler...")
        await hero.goto("https://grailed.com/designers");
        console.log("Navigated to grailed")
        const designer_list = hero.document.querySelector(".designer-list")
        await hero.waitForElement(designer_list, {
        	waitForVisible: true
        })
        const designers = await hero.document.querySelectorAll(".designer-group").$addToDetachedElements('designer-group')
        console.log("Finished detaching elements")
        return hero
      }
    }, HeroExtractorPlugin)
  },
  extractors: {
   extractLatest: new Extractor(
   {
    description: 'blah',
    async run({HeroReplay, Output}) {
      console.log('Starting extractor: extractLatest')
      const heroReplay = await HeroReplay.fromCrawler(datastore.crawlers.getAllBrands, {
        input: {maxTimeInCache: 0}
      })
      console.log('HeroReplay loaded...')
      const designer_groups = await heroReplay.detachedElements.getAll('designer-group')
      for (const i in designer_groups) {
        const designer = designer_groups[i].childNodes
  		designer.forEach(async(a) => {
    		const a_children = a.childNodes.values()
    		const brand = await a_children.next().value.innerText
    		const listings = parseInt(await a_children.next().value.textContent.replace(/[{()}]/g, ''))
    		// console.log(`${brand}: ${listings}`)
    		Output.emit({
    		    brand: brand,
    		    count: listings,
    		    date: new Date()
    		})
  		})
      }
    },
    schema: {
      output: {
        brand: string(),
        count: number({integer: true}),
        date: date(),
      }
    }
  }, HeroExtractorPlugin)
 }
});
export default datastore;

```

Also on the local host page for the api it says:
![Screenshot 2024-08-25 at 23-20-51 Grailed Trends - Ulixee Datastore](https://github.com/user-attachments/assets/ec38a497-1ee4-41a2-8cce-dd0249ef7dea)

Would love any help! Really like the library and product!

**Comment by liamtsang** [comment]
Also trying to debug, and logging 'this.tables' results in [{}]

**Comment by liamtsang** [comment]
crawler cache is a private class by default - can only be accessed internally.
The way I found of accessing it is through an extractor with:
```js
await datastore.crawlers.${MYCRAWLER}.cache.fetchInternal())
```
